stage = input("Enter stage: ")
stage2 = input("Enter stage2: ")
stage3 = input("Enter stage3: ")
stage4 = input("Enter stage4: ")
stage5 = input("Enter stage5: ")
stage6 = input("Enter stage6: ")
stage7 = input("Enter stage7: ")
stage8 = input("Enter stage8: ")
stage9 = input("Enter stage: ")
stage10 = input("Enter stage2: ")
stage11 = input("Enter stage3: ")
stage12 = input("Enter stage4: ")
stage13 = input("Enter stage5: ")
stage14 = input("Enter stage6: ")
stage15 = input("Enter stage7: ")
stage16 = input("Enter stage8: ")
stage17 = input("Enter stage: ")
stage18 = input("Enter stage2: ")
stage19 = input("Enter stage3: ")
stage20 = input("Enter stage4: ")
stage21 = input("Enter stage5: ")
stage22 = input("Enter stage6: ")
stage23 = input("Enter stage7: ")
stage24 = input("Enter stage8: ")
stage25 = input("Enter stage: ")
stage26 = input("Enter stage2: ")
stage27 = input("Enter stage3: ")
stage28 = input("Enter stage4: ")
stage29 = input("Enter stage5: ")
stage30 = input("Enter stage6: ")
stage31 = input("Enter stage7: ")
stage32 = input("Enter stage8: ")

print("== Stages ==")
print("{| align=\"left\" cellpadding=\"1px\" style=\"background:#FFFFFF; text-align:center; border: 3px solid #F03C78; {{roundy}}")
print("|-")
print("! colspan=\"4\"|Stages in [[File:Mode_Icon_Splat_Zones.png|24px]] [[Splat Zones]]")
print("|-")
print("| [[File:S2 Stage " + stage + ".png|150px|link="+stage+"]]<br />[["+stage+"]]")
print("| [[File:S2 Stage " + stage2 + ".png|150px|link="+stage2+"]]<br />[["+stage2+"]]")
print("| [[File:S2 Stage " + stage3 + ".png|150px|link="+stage3+"]]<br />[["+stage3+"]]")
print("| [[File:S2 Stage " + stage4 + ".png|150px|link="+stage4+"]]<br />[["+stage4+"]]")
print("|-")
print("| [[File:S2 Stage " + stage5 + ".png|150px|link="+stage5+"]]<br />[["+stage5+"]]")
print("| [[File:S2 Stage " + stage6 + ".png|150px|link="+stage6+"]]<br />[["+stage6+"]]")
print("| [[File:S2 Stage " + stage7 + ".png|150px|link="+stage7+"]]<br />[["+stage7+"]]")
print("| [[File:S2 Stage " + stage8 + ".png|150px|link="+stage8+"]]<br />[["+stage8+"]]")
print("|")
print("|}")
print("")
print("{| align=\"left\" cellpadding=\"1px\" style=\"background:#FFFFFF; text-align:center; border: 3px solid #F03C78; {{roundy}}")
print("|-")
print("! colspan=\"4\"|Stages in [[File:Mode_Icon_Tower_Control.png|24px]] [[Tower Control]]")
print("|-")
print("| [[File:S2 Stage " + stage9 + ".png|150px|link="+stage9+"]]<br />[["+stage9+"]]")
print("| [[File:S2 Stage " + stage10 + ".png|150px|link="+stage10+"]]<br />[["+stage10+"]]")
print("| [[File:S2 Stage " + stage11 + ".png|150px|link="+stage11+"]]<br />[["+stage11+"]]")
print("| [[File:S2 Stage " + stage12 + ".png|150px|link="+stage12+"]]<br />[["+stage12+"]]")
print("|-")
print("| [[File:S2 Stage " + stage13 + ".png|150px|link="+stage13+"]]<br />[["+stage13+"]]")
print("| [[File:S2 Stage " + stage14 + ".png|150px|link="+stage14+"]]<br />[["+stage14+"]]")
print("| [[File:S2 Stage " + stage15 + ".png|150px|link="+stage15+"]]<br />[["+stage15+"]]")
print("| [[File:S2 Stage " + stage16 + ".png|150px|link="+stage16+"]]<br />[["+stage16+"]]")
print("|")
print("|}")
print("")
print("{| align=\"left\" cellpadding=\"1px\" style=\"background:#FFFFFF; text-align:center; border: 3px solid #F03C78; {{roundy}}")
print("|-")
print("! colspan=\"4\"|Stages in [[File:Mode_Icon_Rainmaker.png|24px]] [[Rainmaker]]")
print("|-")
print("| [[File:S2 Stage " + stage17 + ".png|150px|link="+stage17+"]]<br />[["+stage17+"]]")
print("| [[File:S2 Stage " + stage18 + ".png|150px|link="+stage18+"]]<br />[["+stage18+"]]")
print("| [[File:S2 Stage " + stage19 + ".png|150px|link="+stage19+"]]<br />[["+stage19+"]]")
print("| [[File:S2 Stage " + stage20 + ".png|150px|link="+stage20+"]]<br />[["+stage20+"]]")
print("|-")
print("| [[File:S2 Stage " + stage21 + ".png|150px|link="+stage21+"]]<br />[["+stage21+"]]")
print("| [[File:S2 Stage " + stage22 + ".png|150px|link="+stage22+"]]<br />[["+stage22+"]]")
print("| [[File:S2 Stage " + stage23 + ".png|150px|link="+stage23+"]]<br />[["+stage23+"]]")
print("| [[File:S2 Stage " + stage24 + ".png|150px|link="+stage24+"]]<br />[["+stage24+"]]")
print("|")
print("|}")
print("")
print("{| align=\"left\" cellpadding=\"1px\" style=\"background:#FFFFFF; text-align:center; border: 3px solid #F03C78; {{roundy}}")
print("|-")
print("! colspan=\"4\"|Stages in [[File:Mode_Icon_Clam_Blitz.png|24px]] [[Clam Blitz]]")
print("|-")
print("| [[File:S2 Stage " + stage25 + ".png|150px|link="+stage25+"]]<br />[["+stage25+"]]")
print("| [[File:S2 Stage " + stage26 + ".png|150px|link="+stage26+"]]<br />[["+stage26+"]]")
print("| [[File:S2 Stage " + stage27 + ".png|150px|link="+stage27+"]]<br />[["+stage27+"]]")
print("| [[File:S2 Stage " + stage28 + ".png|150px|link="+stage28+"]]<br />[["+stage28+"]]")
print("|-")
print("| [[File:S2 Stage " + stage29 + ".png|150px|link="+stage29+"]]<br />[["+stage29+"]]")
print("| [[File:S2 Stage " + stage30 + ".png|150px|link="+stage30+"]]<br />[["+stage30+"]]")
print("| [[File:S2 Stage " + stage31 + ".png|150px|link="+stage31+"]]<br />[["+stage31+"]]")
print("| [[File:S2 Stage " + stage32 + ".png|150px|link="+stage32+"]]<br />[["+stage32+"]]")
print("|")
print("|}")
print("{{-}}")
